## solving numpy assignment

1. A Python library is a collection of pre-written code that provides a set of functionalities and tools to perform specific tasks. It contains modules, functions, classes, and methods that can be imported and used in Python programs.  We use Python libraries for several reasons:  1. Reusability: Python libraries allow us to reuse existing code rather than writing everything from scratch. They provide pre-built functions and modules that can be easily integrated into our programs, saving time and effort.  2. Efficiency: Python libraries are often optimized for performance and efficiency. They are developed by experts and undergo rigorous testing, ensuring that they are reliable and provide efficient solutions to common problems.  3. Functionality: Python libraries extend the capabilities of the Python programming language. They provide specialized tools and functionalities for various domains such as data analysis, machine learning, web development, scientific computing, and more. By using libraries, we can leverage these specialized functionalities without having to implement them ourselves. 

2. The main difference between a NumPy array and a Python list is their underlying implementation and the operations they support.

NumPy arrays are homogeneous and fixed-size, meaning that all elements in the array have the same data type, and the size of the array is fixed when it is created. This allows for efficient storage and computation of large datasets. NumPy arrays also support vectorized operations, which means that you can perform operations on entire arrays without the need for explicit loops.

On the other hand, Python lists are heterogeneous and dynamic, meaning that they can contain elements of different data types, and their size can change dynamically as elements are added or removed. Lists are more flexible and can store different types of data, but they are less efficient for numerical computations compared to NumPy arrays.

Here's a summary of the main differences between NumPy arrays and Python lists:

1. Memory Efficiency: NumPy arrays are more memory-efficient compared to Python lists, especially for large datasets, due to their fixed-size and homogeneous nature.

2. Performance: NumPy arrays are faster for numerical computations because they support vectorized operations, which can be executed efficiently by optimized C code. Python lists, on the other hand, require explicit loops for element-wise operations.

3. Data Type: NumPy arrays are homogeneous, meaning that all elements in the array must have the same data type. Python lists can contain elements of different data types.

4. Size and Shape: NumPy arrays have a fixed size and shape when they are created, whereas Python lists can change dynamically as elements are added or removed.


In [18]:
import numpy as np
matrix=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])


In [19]:
## Find the shape, size and dimension of the following array?
matrix.shape
matrix.size
matrix.ndim

2

In [20]:
## 4. Write python code to access the first row of the following array?
matrix[0]

array([1, 2, 3, 4])

In [21]:
## 5. How do you access the element at the third row and fourth column from the given numpy array?
matrix[2][3]

12

In [22]:
## 6. Write code to extract all odd-indexed elements from the given numpy array?
matrix[0::2,0::2]

array([[ 1,  3],
       [ 9, 11]])

In [23]:
## 7. How can you generate a random 3x3 matrix with values between 0 and 1?
np.random.randint(0,1,size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
## 8
## np.random.rand generates random numbers from a uniform distribution between 0 and 1.
## np.random.randn generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.


In [25]:
## 9. Write code to increase the dimension of the following array?
matrix.shape
matrix=matrix.reshape(2,2,3)
matrix.ndim

3

In [26]:
##10. How to transpose the following array in NumPy?
matrix.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [27]:
##11 
matrix1=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
matrix2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
matrix2 * matrix2
matrix2 + matrix1
matrix2 / matrix1
matrix2[1][3] *matrix2[0][2]

24

In [28]:
 ##  12. Which function in Numpy can be used to swap the byte order of an array?
## byteswap()
## example 

In [29]:
hello=np.array([1,2,3,5])
print(list(map(hex,hello)))
hello.byteswap(inplace=True)
print(list(map(hex,hello)))

['0x1', '0x2', '0x3', '0x5']
['0x100000000000000', '0x200000000000000', '0x300000000000000', '0x500000000000000']


13. What is the significance of the np.linalg.inv function?
to get the inverse of a matrix in solving linear algebra equations

In [30]:
from numpy.linalg import solve
a = np.array([[7,-5,-3],[3,-5,2],[5,3,-7]])
z = np.array([[7,-5,-3],[3,-5,2],[5,3,-7]])
np.linalg.solve(a,z)
np.linalg.inv(a)

array([[-0.53703704,  0.81481481,  0.46296296],
       [-0.57407407,  0.62962963,  0.42592593],
       [-0.62962963,  0.85185185,  0.37037037]])

In [31]:
#14. What does the np.reshape function do, and how is it used?
##Gives a new shape to an array without changing its data.
matrix1.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

15 Broadcasting in NumPy is a powerful feature that allows arrays of different shapes to be used together in arithmetic operations. It eliminates the need for explicit loops and enables efficient computation on arrays of different sizes.

In NumPy, broadcasting works by automatically aligning the dimensions of two arrays to perform element-wise operations. When performing operations between arrays with different shapes, NumPy automatically broadcasts the smaller array to match the shape of the larger array.

The broadcasting rules in NumPy are as follows:

1. If the arrays have different numbers of dimensions, the array with fewer dimensions is padded with ones on its left side until the number of dimensions matches.

2. If the shape of the arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the shape of the other array.

3. If the arrays have different sizes in any dimension and neither size is equal to 1, then broadcasting is not possible, and a ValueError will be raised.

In [32]:
import numpy as np
a = np.array([1, 2, 3]) 
b = np.array([10, 20, 30])  
result = a @ b
print(result)

140
